Gd 66
IT-Siberians/UserProfileMicroservice pull request #1
Opened 2024-08-23 17:52 UTC by ConstantinProg

Create domain model

2024-08-24 19:43 UTC, m-a-ilnitsky approved these changes
Есть мелкие придирки, а в целом достойно

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public UserProfile(Guid userId, Email email, Username username, FirstName firstName, LastName lastName, PhoneNumber phoneNumber, PhotoUrl photoUrl, DataPublicityState dataPublicityState)
Длинные списки аргументов лучше писать не в строку, а в столбец.
Так лучше читается.
Но это скорее пожелание чем замечание

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Аргументы для не-nullable свойств лучше проверять на значение null, и бросать исключение если все-таки передали null.
Сейчас конструктор проглотит вместо Email и Username значение null и не поперхнётся.
Аналогично DataPublicityState

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public DataPublicityState DataPublicityState { get; private set; }
Из имени не понятно что же это такое.
Если это те самые флаги о которых было несколько раз обсуждение, то возможно слово Flags было бы уместно и несколько приоткрыло бы завесу тайны.
Если это что-то другое, лучше тоже подумать над более информативным именем.
Я понимаю, что не всегда получается придумать понятное информативно имя...

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Здесь тоже нужна проверка на null для значения аргумента.
Насколько я понимаю указание типа аргумента без ? не гарантирует что в метод не передадут null

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    readonly static int PublicDataFlagsValuesSum = Enum.GetValues(typeof(PublicDataFlags)).Cast<int>().Sum(x => x);
Даже не знаю правильно здесь не указывать модификатор доступа или нет.
С одной стороны если явно указать private ничего не изменится.
С другой стороны практически не встречал чтобы private не указывали явно.

И сейчас имя поля соответствует не публичному члену, лучше все-таки сделать стандартное имя начинающееся с подчеркивания.

И "readonly static" порядок вроде должен быть другой, сначала static потом readonly.
Мне казалось что студия на такие вещи слегка ругается, но не увидел этого, возможно решарпер на такое ругался.
Но когда студия попыталась подсобить и самостоятельно сделать аналогичное поле, она эти модификаторы написала в обратном порядке, несмотря на наличие рядом другого примера

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +        => throw new DataPublicityStateValidationException(message);
Не уверен что метод нужен. Он лишь скрывает тип исключения...
Может лучше его удалить, но необязательно

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        => throw new EmailValidationException(message);
Не уверен что метод нужен. Он лишь скрывает тип исключения...
И сейчас он используется в трёх из четырёх веток в Validate(string value).
А четвертая почему-то то же самое исключение бросает сама без этого метода, лучше сделать единообразно

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
Лучше сделать  в классе статическую константу

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        ThrowValidationException(ExceptionMessages.INVALID_NAME_CAPITALIZATION);
Сбилось форматирование - не хватает отступа

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        string pattern = "(^[A-Z].[a-z]*$)|(^[А-Я].[а-я]*$)";
Лучше сделать статические константы для обоих шаблонов

2024-08-24 19:43 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        string pattern = "(^[A-Z].[a-z]*$)|(^[А-Я].[а-я]*$)";
Аналогично в других классах

2024-08-27 12:10 UTC, oleggolen requested changes
Достаточно неплохо для первого раза, код рабочий, интересная идея с валидацией и валидаторами, присутствуют и Value объекты и доменные исключения, однао доменные исключения надо сделать более понятными, а от некоторых вообще отказаться, соответственно в валидаторах чуть улучшить стиль кода, и возвращать больше деталей по исключениям. Очень надеюсь, что полученные комментарии помогут написать чистый, понятный, легко отлаживаемый код в доменной области

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public UserProfile(Guid userId, Email email, Username username, FirstName firstName, LastName lastName, PhoneNumber phoneNumber, PhotoUrl photoUrl, DataPublicityState dataPublicityState)
В данном случае согласен

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Ну enum быть null в принципе не может, а вот всё остальное реально может быть, согласен, что есть смысл проверить

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    {
Использовать primary конструктор

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Согласен

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public LastName? LastName { get; private set; }
Почему имя и фамилия не обязательны?

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Почему имя и фамилия не обязательны?

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/ValueObject.cs
> +            }
Выравнить скобку

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/ValueObject.cs
> +        return !left.Equals(right);
Зачем такая сложная логика, если можно использовать уже написанный выше оператор?

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/ValueObject.cs
> +            return Object.Equals(left, right);
По идеи null не равны друг другу и никакой объект не может быть равен null, поэтому если пришёл какой-то null, то гарантированно возврашаем false

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/DataPublicityState.cs
> +public   class DataPublicityState(int state) : ValueObject<int>(new DataPublicityValidator(), state);
Лишний пробел

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DomainValidationException.cs
> +public class DomainValidationException(string message) : Exception(message);
Максимально не конкретное исключение. Можно сделать такой класс абстрактным, но как будто бы оно просто дублирует стандартный класс Exception, в чём как будто бы нет смысла

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/EmailValidationException.cs
> +public class EmailValidationException(string message) : DomainValidationException(message);
Здесь очевидно нужно больше параметров, так как информация о том, что Email некорректен слишком мало, нужны детали

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/FirstNameValidationException.cs
> +public class FirstNameValidationException(string message) : DomainValidationException(message);
Тоже самое нужны детали того, что именно не так в имени пользователя, также как и выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/EmailValidationException.cs
> +public class EmailValidationException(string message) : DomainValidationException(message);
Выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/LastNameValidationException.cs
> +public class LastNameValidationException(string message) : DomainValidationException(message);
Тоже самое нужны детали того, что именно не так в имени пользователя, также как и выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhoneNumberValidationException.cs
> +public class PhoneNumberValidationException(string message) : DomainValidationException(message);
Тоже самое нужны детали того, что именно не так в имени пользователя, также как и выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhotoUrlValidationException.cs
> +public class PhotoUrlValidationException(string message) : DomainValidationException(message);
Тоже самое нужны детали того, что именно не так в имени пользователя, также как и выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/UsernameValidationException.cs
> +public class UsernameValidationException(string message) : DomainValidationException(message);
Тоже самое нужны детали того, что именно не так в имени пользователя, также как и выбрать в качестве базового FormatException

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DataPublicityStateValidationException.cs
> +public class DataPublicityStateValidationException(string message) : DomainValidationException(message);
О чём это вообще исключение?

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +        => throw new DataPublicityStateValidationException(message);
Совершенно не нужный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    readonly static int PublicDataFlagsValuesSum = Enum.GetValues(typeof(PublicDataFlags)).Cast<int>().Sum(x => x);
Почему readonly?  Не логичнее ли его сделать просто private static методом? А не каким-то очень странным статическим неизменяемым свойством, в конце концов пойдёт приватная статическая константа, так как это число

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
Согласен, а ещё лучше во внешнем классе хелперов

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        => throw new EmailValidationException(message);
Полностью согласен

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_EMAIL_FORMAT);
Лучше добавить больше параметров и информации к бросаемым исключениям

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        if (value == null)
Не хвататет более детальной информации в исключениях в чём именно была ошибка

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +    }
Вынести регулярные выражения в статические константы или лучше в публичные хелперы

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        => throw new FirstNameValidationException(message);
Бессмысленный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_NAME_CAPITALIZATION);
Добавить больше информации о проблемах, из-за чего возникает исключение

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        string pattern = "(^[A-Z].[a-z]*$)|(^[А-Я].[а-я]*$)";
Вытащить регулярки в приватные константы, а лучше в общие хелперы и просто проверять их на корректность

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        => throw new LastNameValidationException(message);
Бессмысленный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_PHONE_NUMBER_FORMAT);
Добавить больше деталей информации в исключения

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +    }
Вынести регулярку в приватную константу или ещё лучше в публичный хелпер

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +        => throw new PhoneNumberValidationException(message);
Убрать бессмысленный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +        => throw new PhotoUrlValidationException(message);
Убрать бессмысленный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +    }
Добавить больше информации об ошибки в исключение

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_USERNAME_CHARACTER_SET);
Добавить больше информации и возникшей ошибки в исключение

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +    }
Вынести регулярку в приватную константу или в публичный хелпер

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => throw new UsernameValidationException(message);
Убрать бессмысленный метод

2024-08-27 12:10 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => name.Where(ch => Char.IsLetterOrDigit(ch)).Count();
Можно сделать метод статическим да и особого смысла в нём нет

2024-08-28 07:59 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public UserProfile(Guid userId, Email email, Username username, FirstName firstName, LastName lastName, PhoneNumber phoneNumber, PhotoUrl photoUrl, DataPublicityState dataPublicityState)
Разбил на две строки. Вроде не слишком длинно теперь.

2024-08-28 08:06 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Добавил для всех не nullable свойств проверки вроде следующей:
        ArgumentNullException.ThrowIfNull(email);
        Email = email;

2024-08-28 08:11 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public DataPublicityState DataPublicityState { get; private set; }
Это ValueObject, который обарачивает PublicDataFlags в моей голове это переводится, как состояние публичности данных. Ничего лучше я не придумал.

2024-08-28 08:15 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Добавил:
ArgumentNullException.ThrowIfNull(newDataPublicityState);
        Аналогично для ChangeFirstName и ChangeLastName.

2024-08-28 08:22 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    readonly static int PublicDataFlagsValuesSum = Enum.GetValues(typeof(PublicDataFlags)).Cast<int>().Sum(x => x);
К сожалению константу сдесь сделать не получится, так как выражение справа вычисляется в Runtime. По сути в таких случаях используют static readonly.  Поправил на:
private static readonly int PublicDataFlagsValuesSum =

2024-08-28 08:24 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +        => throw new DataPublicityStateValidationException(message);
Удалил везде подобные методы.

2024-08-28 09:51 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Лучше добавлять в исключение имя аргумента:
ArgumentNullException.ThrowIfNull(email, nameof(email));

И в целом, хотя в некоторых методах использование ArgumentNullException.ThrowIfNull может быть эффективнее.
В конструкторе удобнее использовать более краткий синтаксис.

Т.е. вместо такого:
ArgumentNullException.ThrowIfNull(email, nameof(email));
Email = email;

Писать так:
Email = email ?? throw new ArgumentNullException(nameof(email));

2024-08-28 10:08 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    readonly static int PublicDataFlagsValuesSum = Enum.GetValues(typeof(PublicDataFlags)).Cast<int>().Sum(x => x);
Константин прав.
В статическую константу можно положить только литералы и результаты некоторых выражений над литералами, т.к. их можно вычислить на этапе компиляции.
У большинства классов нет литералов, их объекты создаются на этапе выполнения, поэтому даже если результат int, но его значение вычисляется с помощью класса который создается в runtime, то это значение не получится сделать статической константой.
Но вот static readonly это значение положить получится, т.к. значение такого поля заполняется в runtime при первом обращении к данному классу.

По сути static readonly поля в C# - это прямой аналог static final полей в Java.
А вот const поля не имеют прямых аналогов в Java.

2024-08-29 14:05 UTC, Barmalej24 reviewed
В целом код понравился. Поддерживаю предложения по внесению конкретики в кастомные исключения, вынос регулярных вырожений константами в отдельный калас

2024-08-29 14:05 UTC, Barmalej24 commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Согласен что проверки необходимы,  вариант ?? throw new ArgumentNullException(nameof(email)), кажется самым оптимальным

2024-08-29 14:05 UTC, Barmalej24 commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
Согласен с предложеними выше.

2024-08-30 06:33 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        Username = username;
Переделал на вариант ?? throw new ArgumentNullException(nameof(email))

2024-08-30 06:52 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
Сделал приватные константы. Хелперы идея хорошая, но я бы сначала хотел её обсудить.

2024-08-30 06:53 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        ThrowValidationException(ExceptionMessages.INVALID_NAME_CAPITALIZATION);
Поправил.

2024-08-30 06:55 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        string pattern = "(^[A-Z].[a-z]*$)|(^[А-Я].[а-я]*$)";
Сделал приватные константы. Хелперы чуть позже.

2024-08-30 07:01 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    {
Есть ли смысл делать первичный конструктор с учётом проверок на null? Имею в виду, что количество кода не уменьшится. Возможно я не прав и не знаю каких-то вещей о синтаксисе первичных конструкторов.

2024-08-30 07:02 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public LastName? LastName { get; private set; }
Теперь обязательны.

2024-08-30 07:03 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +    }
Могу только саму url строку добавить.

2024-08-30 07:08 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => name.Where(ch => Char.IsLetterOrDigit(ch)).Count();
Этот метод сделан для упрощения чтения кода валидации. Делать этот метод static не вижу смысла. Возможно я чего-то не знаю.

2024-08-30 13:56 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => name.Where(ch => Char.IsLetterOrDigit(ch)).Count();
Статическим его можно сделать из простых соображений, что он не работает с полями объекта, а вызов статического метода более простая операция.
Поэтому в таких случаях сама студия предлагает делать метод статическим, для оптимизации

2024-08-31 08:42 UTC, closed without merging