Task/gd 203
IT-Siberians/UserProfileMicroservice pull request #10
Opened 2024-10-09 08:48 UTC by ConstantinProg

Fix soft deletion and mapping issues

2024-10-09 10:55 UTC, Barmalej24 requested changes
В целом, код выглядит чистым и хорошо структурированным. Однако, есть несколько моментов, которые я думаю стоит изменить.

2024-10-09 10:55 UTC, Barmalej24 commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +}
Может проще использовать автомаппер?

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/Base/Entity.cs
Ты отказался от доменного слоя?

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/UserProfile.cs
Ты отказался от доменного слоя?

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        return true;
Добавить проверку, чтобы убедиться, что сущность была действительно обновлена.

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +    protected ApplicationDbContext Context => context;
Лишнее определение

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        Context.Update(entity);
Использовать контекст из конструктора

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        => await Context.Set<TEntity>().FindAsync(id);
Использовать контекст из конструктора

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        => (await Context.Set<TEntity>().AsNoTracking().ToListAsync()).AsEnumerable();
Использовать контекст из конструктора

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        await Context.SaveChangesAsync();
Использовать контекст из конструктора

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        => Context.UserProfiles.FirstOrDefaultAsync(x => x.Username.Value.Equals(username));
Почему бы не использовать переданный контекст из конструктора?

2024-10-09 10:55 UTC, Barmalej24 commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        && await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
Почему бы не использовать переданный контекст из конструктора?

2024-10-09 13:59 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        && await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
Выдаёт warning.

2024-10-09 14:00 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +}
Считаю, что в конкретно этом случае совсем не проще.

2024-10-09 14:01 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/Base/Entity.cs
Нет. Всё, как и раньше. Просто у меня трёхслойная архитектура.

2024-10-09 14:02 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        return true;
Да я планировал.

2024-10-09 14:04 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +    protected ApplicationDbContext Context => context;
Не лишнее. Это необходимо, что бы спокойно использовать Context в отнаследованном классе.

2024-10-09 14:12 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        && await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
https://stackoverflow.com/questions/77302452/how-to-properly-idiomatic-avoid-cs9107-when-passing-primary-constructor-para

2024-10-09 15:31 UTC, oleggolen approved these changes
Не вижу ничего особо криминального кроме проверок на реальные удаления

2024-10-11 15:00 UTC, Barmalej24 approved these changes

2024-10-11 18:04 UTC, m-a-ilnitsky approved these changes

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/UserProfileService.cs
> +    }
Эти return с тернарными операторами можно сократить до такой записи:
return profile?.MapToModel();

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        && await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
Лучше добавить отступ, чтобы эти две строки имели сдвиг вправо относительно объявления метода

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        && await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
Вместо:
await Context.UserProfiles.FirstOrDefaultAsync(x => x.Email == profile.Email) is null
можно писать:
!await Context.UserProfiles.AnyAsync(x => x.Email == profile.Email)

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +        => Context.UserProfiles.FirstOrDefaultAsync(x => x.Username.Value.Equals(username));
x.Username.Value.Equals(username)
Этот код точно работает?
Или пока не проверял?
Вроде что-то такое не работало у Николая, когда настройки сущностей EF делались через HasConversion

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        await Context.SaveChangesAsync();
Здесь не хватает метода Update, например Context.Set<TEntity>().Update(entity)

2024-10-11 18:04 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/InMemory/InMemoryUserProfileRepository.cs
> +        && EntityList.FirstOrDefault(x => x.Email == profile.Email) is null
Здесь вместо FirstOrDefault лучше использовать Any

2024-10-12 08:14 UTC, merged

2024-10-12 19:40 UTC, m-a-ilnitsky commented on src/DataAccess/UserProfileMicroservice.DataAccess.Repositories.Implementations/EntityFramework/EFRepository.cs
> +        await Context.SaveChangesAsync();
Я не прав, всё-таки и без Update должно работать