Task/gd 219
IT-Siberians/UserProfileMicroservice pull request #12
Opened 2024-11-07 05:44 UTC by ConstantinProg

Create WebApi

2024-11-07 15:41 UTC, oleggolen requested changes
Исправляем это всё до хорошего и красивого кода

2024-11-07 15:41 UTC, oleggolen commented on docker/cmd/start.bat
Тогда лучше файл назвать restart

2024-11-07 15:41 UTC, oleggolen commented on docker/cmd/stop.bat
Да и вообще мне не нравится идея бат файлов так как это только под виндовс, а под линукс что sh скрипты писать?

2024-11-07 15:41 UTC, oleggolen commented on docker/.env
Добавить в игнор и удалить из репозитория

2024-11-07 15:41 UTC, oleggolen commented on docker/docker-compose.yml
А где проверки самих healthchecks при проверке на то что сервис здоров?

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Controllers/UserProfileController.cs
> +    }
Стрелочная функция

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Helpers/MigrationManager.cs
Лучше это всэ сделать асинхронным, так как это долгая операция

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Requests/UpdateProfileRequest.cs
> +    bool IsPhoneNumberPublished);
Совершенно не читаемо. Если используется валидация аттрибутами, тогда уж лучше сделать классами, а не структурами. Также в контроллере необходимо вызвать валидацию модели. А лучше всего использовать FluentValidation

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Requests/CreateProfileRequest.cs
> +    bool IsPhoneNumberPublished);
Совершенно не читаемо. Если используется валидация аттрибутами, тогда уж лучше сделать классами, а не структурами. Также в контроллере необходимо вызвать валидацию модели. А лучше всего использовать FluentValidation

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/appsettings.Development.json
Добавить этот файл в игнор

2024-11-07 15:41 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/appsettings.json
> +  },
Убрать в переменные окружения

2024-11-07 15:41 UTC, oleggolen commented on src/Dockerfile
> +RUN dotnet restore "./WebApi/UserProfileMicroservice.WebHost/UserProfileMicroservice.WebHost.csproj"
Заменить это на копирование сразу всего проекта и прямую сборку

2024-11-08 06:10 UTC, ConstantinProg commented on docker/cmd/stop.bat
Эти файлы просто для моего удобства. Всё  тоже самое можно легко делать из терминала.

2024-11-08 06:11 UTC, ConstantinProg commented on docker/.env
Оставил осознано, чтобы коллеги могли запустить сервис.

2024-11-08 14:29 UTC, closed without merging