#GD-195 Fix some communication issues. Refactore some pr issues
IT-Siberians/UserProfileMicroservice pull request #14
Opened 2024-11-17 11:28 UTC by ConstantinProg

2024-11-17 12:07 UTC, m-a-ilnitsky approved these changes

2024-11-17 13:58 UTC, oleggolen requested changes
Ну в целом нормально, но тогда уж всё исправить надо было, что я говорил, раз 3х подтверждений пока нет, поэтому потребую доведения до идеала и не появления новых ошибок

2024-11-17 13:58 UTC, oleggolen commented on docker/docker-compose.yml
>      restart: always
Лучше иметь политику перезапуска unless-stopped

2024-11-17 13:58 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/UserProfileService.cs
>          await notificationService.PublishUserIsUpdatedAsync(profile.ToModel());
А для чего в этом методе возвращать всю модель? Достаточно bool или какой-нибудь bool?

2024-11-17 13:58 UTC, oleggolen commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/UserProfile.cs
> +        => Email = new Email(emailValue);
Опять же не понимаю почему доменная сущность оперирует строками а не ValueObject'ами

2024-11-17 13:58 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Helpers/MigrationManager.cs
>          return host;
Сделать это все асинхронным

2024-11-17 13:58 UTC, oleggolen commented on src/WebApi/UserProfileMicroservice.WebHost/Mapping/MappingExtensions.cs
>              $"{profileModel.FirstName} {profileModel.LastName}",
Не проще ли добавить какое-нибудь свойство в модель типо FullName или там extension какой-то написать, но не дублировать одну и ту же логику 2 раза

2024-11-18 01:10 UTC, ConstantinProg commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/UserProfile.cs
> +        => Email = new Email(emailValue);
Мне хотелось, чтобы методы хоть какую-то работу делали, кроме присваивания. Ну и bll слой выглядит симпотичнее.

2024-11-18 02:47 UTC, ConstantinProg commented on docker/docker-compose.yml
>      restart: always
Сделано.

2024-11-18 02:47 UTC, ConstantinProg commented on src/WebApi/UserProfileMicroservice.WebHost/Helpers/MigrationManager.cs
>          return host;
Сделал.

2024-11-18 02:48 UTC, ConstantinProg commented on src/WebApi/UserProfileMicroservice.WebHost/Mapping/MappingExtensions.cs
>              $"{profileModel.FirstName} {profileModel.LastName}",
Было не проще, но я сделал :)

2024-11-18 02:49 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/UserProfileService.cs
>          await notificationService.PublishUserIsUpdatedAsync(profile.ToModel());
Справедливо. Поправил.

2024-11-18 06:56 UTC, NikeTorchwood commented on src/DataAccess/UserProfileMicroservice.DataAccess.Entities/UserProfile.cs
> +        => Email = new Email(emailValue);
согласен, помнишь у меня ошибка была с перепутанным Lastname и Firstname, потому что я строки в домейн передавал

2024-11-18 06:58 UTC, NikeTorchwood commented on src/WebApi/UserProfileMicroservice.WebHost/Controllers/UserProfileController.cs
>      [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(Guid))]
@oleggolen тут вопрос больше к вам, а как здесь защититься от неаутентифицированных пользователей?

2024-11-18 07:14 UTC, NikeTorchwood approved these changes
аппрув,
из пожеланий, верное замечание Олега, лучше использовать аутомаппер как по мне

2024-11-18 07:18 UTC, Barmalej24 approved these changes

2024-11-18 11:05 UTC, ConstantinProg commented on src/WebApi/UserProfileMicroservice.WebHost/Controllers/UserProfileController.cs
>      [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(Guid))]
Есле в заголовках http будет присутствовать UserId, то его можно сравнивать с передаваемым в этот метод.

2024-11-18 11:06 UTC, merged