Gd 105
IT-Siberians/UserProfileMicroservice pull request #2
Opened 2024-08-23 18:14 UTC by ConstantinProg

Create in memory repository

2024-08-24 20:25 UTC, m-a-ilnitsky approved these changes
Несколько дополнительных замечаний к замечаниям из пул-реквеста к ветке 66.
Старался не повторять замечания из того пул-реквеста

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +public class UserProfile : IEntity<Guid>
Написал  в предыдущем пул-реквесте, здесь не буду повторяться

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +    private readonly IValidator<T> _validator;
Поле _validator фактически не нужно, оно используется только в конструкторе, поэтому можно обойтись самим аргументом

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +            throw new ValidatorNotSpecifiedException(this);
Вместо:
        _validator = validator;
        if (_validator == null)
            throw new ValidatorNotSpecifiedException(this);
Удобнее писать так:
       _validator = validator ?? throw new ValidatorNotSpecifiedException(this);

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        Value = value;
Для Value тоже удобнее использовать краткий синтаксис с ??

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        return isMatch.Success;
Забыл написать в предыдущем пул-реквесте:

1) Странно что в методах IsValidCharacterSet и IsValidNameCapitalization не используются var

2) Если бы использовался var то по имени isMatch казалось бы что это переменная типа bool.
Здесь лучше переменную isMatch назвать по имени класса, т.е. match

3) Кажется что переменная isMatch в целом не нужна, можно в return подставить сам метод:
return  Regex.Match(...).Success;

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        return isMatch.Success;
Аналогично в других классах

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        {
Сбилось форматирование: неправильные отступы у скобки.
И у некоторых методов отступы тоже неправильные.
Лучше применить автоформатирование

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId>
В данном случае этот новый синтаксис конструктора довольно плохо читается.
У меня такое ощущение что его удобно использовать только в совсем коротких классах, у которых только один конструктор.
Может просто я пока не привык, но не сразу понял откуда у нас взялся второй конструктор вызванный в конструкторе по умолчанию

2024-08-24 20:25 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +namespace DataAccess.Entities.ValueObjects.Base;
Папки Entities и ValueObjects по идее должны быть на одном уровне вложенности

2024-08-27 12:20 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        Value = value;
Microsoft сами так пишут

2024-08-27 12:42 UTC, oleggolen requested changes
Очень хорошо, что реализована доменная модель, Value объекты, доменные исключения и валидаторы, также созданы абстракции репозиториев и InMemory реализация. Стоит навести форматирование в коде, сделать иерархию исключений более понятной и конкретной, а также добавить больше детальной информации в исключения, не писать различные лишние методы и алгоритмы самому, а использовать готовые. Очень надеюсь, что указанные мною комментарии помогут писать легко читаемый, чистый код, соблюдающий принципы ООП, SOLID и DDD

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return !left.Equals(right);
Можно использовать уже написанный готовый оператор

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return Value?.ToString() ?? GetType().ToString();
По логике конструктора Value null быть не может, соответственно сложная логика не нужна, или заменить на бросание исключения

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +            return Equals(left, right);
По идеи при любом сравнении с null мы модлжны получать false, также как и null и null не равны

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DataPublicityStateValidationException.cs
> +public class DataPublicityStateValidationException(string message) : DomainValidationException(message);
О чём это исключение?

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DomainValidationException.cs
> +public class DomainValidationException(string message) : Exception(message);
Максимально непонятное и неконкретное исключение, которое по сути есть Exception, не вижу смысла делать это типом исключения, ну или хотя бы сделать такой класс абстрактным

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/EmailValidationException.cs
> +public class EmailValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/FirstNameValidationException.cs
> +public class FirstNameValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/LastNameValidationException.cs
> +public class LastNameValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhoneNumberValidationException.cs
> +public class PhoneNumberValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhotoUrlValidationException.cs
> +public class PhotoUrlValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/UsernameValidationException.cs
> +public class UsernameValidationException(string message) : DomainValidationException(message);
Добавить больше деталей в информацию по исключению, также наследовать от FormatException

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IRepository.cs
> +    }
Выравнить скобки

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IRepository.cs
> +    where TEntity : IEntity<TId>
Добавить ограничение на тип TId, для корректной работы базы данных, что он является примитивным типом

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IRepository.cs
> +    where TEntity : IEntity<TId>
TId добавить параметр in

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IRepository.cs
> +    Task<TEntity> AddAsync(TEntity entity);
Добавить какой-то вариант в случае ошибки

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/IEntity.cs
> +public interface IEntity<TId>
Пометить ключевым словом out, а также добавить ограничение на то, что Id является примитивным типом для корректной работе базы данных

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Не уверен, что имя и фамилия должны быть nullable

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public UserProfile(Guid id, Email email, Username username, FirstName firstName, LastName lastName, PhoneNumber phoneNumber, PhotoUrl photoUrl, DataPublicityState dataPublicityState)
Использовать primary конструктор

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public LastName? LastName { get; private set; }
Не уверен, что эти поля должны быть nullable

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Скорее всего тут имелось в виду присваивание аргументу, а не поля самого себе

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IUserProfileRepository.cs
> +}
Какой смысл в этом интерфейсе на данный момент?

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId>
Всё отлично читается, всё тут хорошо

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId>
К TId добавить ключевое слово in а также добавить ограничение на то, что он является примитивным типом для корректной работы базы данных

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +            }
Заменить на работу с LINQ

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryUserProfileRepository.cs
> +    : InMemoryRepository<UserProfile, Guid>(userProfiles), IUserProfileRepository
Смысл этого класса на данный момент?

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/DataPublicityState.cs
> +public   class DataPublicityState(int state) : ValueObject<int>(new DataPublicityValidator(), state);
Убрать лишний пробел

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +        => throw new DataPublicityStateValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +
Добавить больше информации об ошибке в исключение

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    readonly static int PublicDataFlagsValuesSum = Enum.GetValues(typeof(PublicDataFlags)).Cast<int>().Sum(x => x);
Сделать поле приватной константой

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_EMAIL_FORMAT);
Добавить больше информации об ошибках в исключения

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +    private bool IsValidEmailAddressFormat(string email)
Убрать регулярку в публичные хелперы и в целом убрать сей метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        => throw new EmailValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        ThrowValidationException(ExceptionMessages.INVALID_NAME_CAPITALIZATION);
Добавить больше информации в исключения

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +    }
Убрать исключения в отдельные публичные хелперы, и там их использовать, сами методы проверки регулярки либо убрать либо сделать единый статический метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        => throw new FirstNameValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        => throw new LastNameValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +    }
Вынести регулярки в публичные хелперы для дальнейших проверок, а метод проверки регулярки вынести в общий статический метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +    }
Добавить больше информации в исключения

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +        => throw new PhoneNumberValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +    }
Вынести регулярку в отдельный набор публичных хелперов для использования в других местах

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +    }
Добавить больше информации об ошибке в исключение

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +        => throw new PhotoUrlValidationException(message);
Убрать лишний метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +    }
Добавить больше информации об ошибке в исключение

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => throw new UsernameValidationException(message);
Убрать неиспользуемый метод

2024-08-27 12:42 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +    }
Убрать регулярку в публичный хелпер для использования на других урованях, метод оставить приватным статическим, или его логику перенести в условие в валидации

2024-08-29 14:13 UTC, Barmalej24 reviewed
Повторение из предыдущего пулреквеста: больше конкретики в кастомных исключен иях, наследования от максимально близких базовых исключений.

2024-08-29 14:13 UTC, Barmalej24 commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +namespace DataAccess.Entities.ValueObjects.Base;
Согласен с Михаилом.

2024-08-30 07:14 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +    private readonly IValidator<T> _validator;
Поле убрано.

2024-08-30 07:14 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +            throw new ValidatorNotSpecifiedException(this);
Поле убрано. Теперь не актуально.

2024-08-30 07:16 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        Value = value;
Сделал краткий вариант. Он мне нравится.

2024-08-30 07:24 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        return isMatch.Success;
Теперь эти методы реализованы в одну строку.

2024-08-30 07:29 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        {
Применил.

2024-08-30 07:35 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId>
Добавлено в IRepository

2024-08-30 08:21 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return Value?.ToString() ?? GetType().ToString();
Компелятор ругается. Могу написать Value!.ToString()

2024-08-30 08:24 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +            return Equals(left, right);
Хм. Действительно это логично, что null и null должны возвращать false.

2024-08-30 08:27 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DataPublicityStateValidationException.cs
> +public class DataPublicityStateValidationException(string message) : DomainValidationException(message);
Имелось в виду исключение при валидации DataPublicityState. Впрочем нужно пересматривать всю систему исключений.

2024-08-30 08:29 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +        => throw new PhotoUrlValidationException(message);
Убраны везде.

2024-08-30 08:31 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +    }
Возможно стоит убрать валидаторы для общего использования. Давайте это обсудим.

2024-08-30 10:02 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +            return Equals(left, right);
Ну null и null обычно, по умолчанию, считаются равными друг другу значениями.
Во встроенном статическом Equals они равны.
В нестатическом Equals получается false только потому, что объект от которого взывают этот Equals точно существует.
Отсутствие значения это тоже некоторое значение.
По идее если типы аргументов совпадают, и в оба аргумента переданы null, то это две идентичные ситуации отсутствия значения, поэтому должен получаться true.
А если типы не совпадают, то этот метод наверное не должен вызываться...
Может в моих рассуждениях и есть какая-то ошибка, но я сам её не вижу

2024-08-31 08:41 UTC, closed without merging