Task gd 131
IT-Siberians/UserProfileMicroservice pull request #3
Opened 2024-08-23 18:21 UTC by ConstantinProg

Create EntityFramework repository

2024-08-24 21:17 UTC, m-a-ilnitsky approved these changes
Несколько дополнительных замечаний к замечаниям из предыдущих пул-реквестов.
Лучше потом их все разом исправить в новой ветке

P.S.
И сейчас получилось что есть три пул-реквеста для веток 66, 105, 131, относительно ветки dev.
И так-как эти ветки идут последовательно, то пул-реквесты друг друга дублируют.
Получается что часть кода я просмотрел 2 раза, а часть кода 3 раза.
Хотя со 2го и 3го раза всегда находишь что-то новое, на что не обратил внимание в первый раз)), но это все-таки неудобно.
В текущей ситуации лучше было создать один пул-реквест для последней ветки 131.
И остальным сейчас имеет смысл проверять только его

P.S.2.
И еще такой момент, что я не понимаю в каком виде вы Константин видите эти комментарии к пул-реквесту.
Поэтому если вам будет непонятно к чему относится тот или иной комментарий, в напишите это в ответе на комментарий. Ну или в чате, если в гите с этим будут проблемы.
Я тогда постараюсь более подробно пояснить, может с указанием строк кода

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/Base/Entity.cs
> +    public static bool operator !=(Entity<TId> first, Entity<TId> second)
Между объявлениями операторов лучше добавить пустую строку

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +namespace DataAccess.Entities;
Не буду дублировать замечания из предыдущих пул-реквестов

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return !left.Equals(right);
В обоих операторах если просто сразу вызвать статический метод Equals(left, right) то будет тот же самый результат.
Т.к. эта же самая логика реализована внутри статического метода.
Поэтому в обоих операторах не нужны две ветки, достаточно просто сразу вызвать статический Equals

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/FirstName.cs
> +    public const int MaximumValueLength = 30;
В валидаторе константа используется как FirstName.MaximumValueLength.
Можно сократить имя чтобы получалось FirstName.MaxLength

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/FirstName.cs
> +}
В целом, вся эта логика когда FirstName ссылается на FirstNameValidator, а FirstNameValidator ссылается на FirstName кажется странной и запутанной.
Можно конечно FirstName.MaximumValueLength передавать внутрь FirstNameValidator в качестве аргумента конструктора.
Но FirstNameValidator всегда бросает FirstNameValidationException и для других валуэ-обджектов он не применим, т.е. все равно жестко привязан к FirstName.
Может в таком случае лучше не делать два класса, а объединить всё внутри FirstName.

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/FirstName.cs
> +}
Аналогично для других классов

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.EntityFramework/Configurations/UserProfileConfiguration.cs
> +    private T? ConvertNullableValueObject<T>(ValueObject<T>? valueObject)
ConvertNullableValueObject - возможно лучше назвать ConvertToNullableValue или GetNullableValue

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Entities/ValueObjects/FirstName.cs
> +    public const int MaximumValueLength = 30;
Аналогично в других классах

2024-08-24 21:17 UTC, m-a-ilnitsky commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        => Task.FromResult(EntityList.AsEnumerable());
Здесь неправильно использовать AsEnumerable(), это нарушает инкапсуляцию.
AsEnumerable выполняет приведение типа коллекции к типу IEnumerable\<TSource\>.
Т.е. полученную из этого метода ссылку потом можно привести обратно к типу List\<TSource\> и изменить список в обход методов репозитория.
Здесь лучше использовать ToList() который всегда создает новый список с элементами исходной коллекции, или ToArray()

2024-08-26 15:45 UTC, NikeTorchwood reviewed
Отличный код, Константин. 
Сделана большая работа, в целом очень чистый код, есть маленькие недочеты - использование помоему называется "базовых" классов, избыточна явная типизация, отсутствие документации и как мне кажется нарушение логики в валидации(запрет создания nullable объекта)

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/Base/Entity.cs
> +public abstract class Entity<TId>(TId id) : IEquatable<Entity<TId>>
добавить документацию

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +public class UserProfile : Entity<Guid>
добавить документацию

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +public abstract class ValueObject<T> : IEquatable<ValueObject<T>>
добавить документацию

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +internal class EmailValidator : IValidator<String>
насколько я знаю класс String используют при использовании в кроссплатформе, для нашего уровня можно использовать string

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +    private void ThrowValidationException(string message)
а какой в этом смысл? можно же не оборачивать методом, он же не содержит логики

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
вообще я думаю что это константа, если это не константа(здесь не объявлено что это константа) - то лучше использовать var(и везде лучше делегировать определение типа VS Studio, где не применяется полиморфизм)

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
или подстановка лисков, ну смысл поймешь(помни образование моё три класса)

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        if (value == String.Empty)
зачем разделять логику и проверять отдельно null и отдельно empty?
есть придуманный метод string.isnullorwhitespace, который закроет несколько способов сломать программу, думаю лучше использовать это(разделение избыточно)

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        if (value == null)
что смущает, в Profile ты допускаешь что Firstname может являться null, при этом при создании Firstname он будет явно валидироваться и тут ты запрещаешь создание пустой или null значения. Здесь мне мешает мои 3 класса образования, поэтому я думаю тебе стоит самому над этим подумать

2024-08-26 15:45 UTC, NikeTorchwood commented on src/DataAccess/DataAccess.EntityFramework/Configurations/UserProfileConfiguration.cs
> +        builder.HasKey(x => x.Id);
Михаил прав и переносы строки добавляют читаемости кода

2024-08-28 05:22 UTC, oleggolen requested changes
Дотстаточно хороший код, реализующий EntityFramework, валидацию, домаенные сущности, доменные исключения, репозитории как InMemmory, так и EF. Хочется отметить, что стоит добавить в исключения больше детальной информации о том, что привело к ошибке, добавить фабричный метод на исключения, наследовать исключения от более конкретных типов стандартных исключений(либо в случае фабричного метода может быть оставить и так). Также вынести все константы в публичные хелперы и сделать полезный метод расширения на строку, перейти на большее использование LINQ. Очень надеюсь, что мои советы помогут писать код по ООП и SOLID, а также иметь прекрасное представление о DDD и его принципах

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/Base/Entity.cs
> +    public static bool operator !=(Entity<TId> first, Entity<TId> second)
Наверное пробельный символ а не пустую строку?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return !left.Equals(right);
В принципе тут можно вызывать просто отрицание от результата оператора равно

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryUserProfileRepository.cs
> +    : InMemoryRepository<UserProfile, Guid>(userProfiles), IUserProfileRepository
Какой смысл данного класса на данный момент?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        => Task.FromResult(EntityList.AsEnumerable());
Чушь

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +            }
Перейти на использование LINQ

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +            }
Перейти на вызов уже ранее написанного метода или LINQ

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Implementations/EntityFramework/EFUserProfileRepository.cs
> +}
Какой смысл данного класса на данный момент?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Repositories.Abstractions/IUserProfileRepository.cs
> +}
Смысл этого интерфейса на данный момент?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.EntityFramework/Configurations/UserProfileConfiguration.cs
> +            .HasConversion(lastName => ConvertNullableValueObject(lastName), value => value == null ? null : new LastName(value))
Это точно может быть null?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.EntityFramework/Configurations/UserProfileConfiguration.cs
> +    }
Смысл этого действа?

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    public LastName? LastName { get; private set; }
Не должно быть nullable

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Нельзя тут принимать nullable

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +    }
Здесь имелось в виду присваивание параметра, а не поля самому же себе

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/UserProfile.cs
> +        DataPublicityState = dataPublicityState;
Добавить проверки на null

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/FirstName.cs
> +}
Да согласен, надо либо использовать эту константу только в валидаторе, либо подобного рода константы выносить в публичные хелперы, чтобы была возвожность проверять эти условия и на других уровнях

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/LastName.cs
> +    public const int MaximumValueLength = 30;
Вынести в публичный хелпер

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/PhoneNumber.cs
> +    public const int MaximumValueLength = 14;
Вынести в публичный хелпер

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Username.cs
> +    public const int MaximumValueLength = 30;
Вынести в публичный хелпер

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Email.cs
> +    public const int MaximumValueLength = 255;
Вынести в публичный хелпер

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/DataPublicityState.cs
> +public   class DataPublicityState(int state) : ValueObject<int>(new DataPublicityValidator(), state);
Уьрать лишний пробел

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DataPublicityStateValidationException.cs
> +public class DataPublicityStateValidationException(string message) : DomainValidationException(message);
Абсолютно непонятное исключение, полностью непонятно что это делает и для чего

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/DomainValidationException.cs
> +public class DomainValidationException(string message) : Exception(message);
Максимально непонятное и неконкретное исключение, можно сделать этот класс либо абстрактным, либо убрать, потому что сейчас это просто дублирует стандартный базовый класс

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/EmailValidationException.cs
> +public class EmailValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/FirstNameValidationException.cs
> +public class FirstNameValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/LastNameValidationException.cs
> +public class LastNameValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhoneNumberValidationException.cs
> +public class PhoneNumberValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/PhotoUrlValidationException.cs
> +public class PhotoUrlValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Exceptions/UsernameValidationException.cs
> +public class UsernameValidationException(string message) : DomainValidationException(message);
Добавить больше информации в исключение, наследовать от FormatException

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +        => throw new DataPublicityStateValidationException(message);
Лишний метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/DataPublicityStateValidator.cs
> +    }
Добавить больше информации в исключение

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        string pattern = "[.\\-_a-z0-9]+@([a-z0-9][\\-a-z0-9]+\\.)+[a-z]{2,6}";
Лучше её вынести в какой-нибудь публичный хелпер для того, чтобы потом использовать в других слоях

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +    private void ThrowValidationException(string message)
Да, нужно убрать лишний метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +    }
Перенести регулярные выражения в публичный хелпер для того, чтобы использовтаь других слоях приложения

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        => throw new FirstNameValidationException(message);
Убрать лишний метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +            ThrowValidationException(ExceptionMessages.INVALID_NAME_CAPITALIZATION);
Добавить больше информации в методы исключения

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +
Вынести регулярные выражения в публичный хелпер для того, чтобы можно было переиспользовать на других слоях

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +        => throw new LastNameValidationException(message);
Убрать неиспользуемый метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/LastNameValidator.cs
> +    }
Добавить больше информации по исключениям и в сами исключения и в методы, чтобы было и по названию и сообщению и из отладчика понять что и почему как случилось

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +    }
Вынести регулярку в публичный метод и сделать метод статическим приватным

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +        => throw new PhoneNumberValidationException(message);
Убрать неиспользуемый метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhoneNumberValidator.cs
> +    }
Добавить больше детальной информации в исключения и в методы исключения

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +        => throw new PhotoUrlValidationException(message);
Убрать неиспользуемый метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/PhotoUrlValidator.cs
> +    }
Добавить больше информации в сами исключения и в методе передавать больше конкретики по исключениям

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +    }
Вынести регулярное выражение в публичный хелпер и сделать метод статическим приватным

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => throw new UsernameValidationException(message);
Убрать лишний метод

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => name.Where(ch => Char.IsLetterOrDigit(ch)).Count();
Можно сделать это методом расширения на строку, так как много где используется и дублируется

2024-08-28 05:22 UTC, oleggolen commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +    }
Добавить больше информации в классы-исключения больше информации о деталях ошибки, а также в методе передавать больше деталей о исключении, кстати реально можно задумать о каком-нибудь ExceptionFactory, чтобы реализовать паттерн фабричный метод и бросать соответствующие исключение с нужными параметрами в зависимости от условия, приводящего к исключению

2024-08-29 14:26 UTC, Barmalej24 reviewed
Поддерживаю предложения по внесению конкретики в кастомные исключения, вынос регулярных вырожений константами в отдельный калас

2024-08-30 08:35 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Base/ValueObject.cs
> +        return !left.Equals(right);
Переделаю.

2024-08-30 08:46 UTC, ConstantinProg commented on src/DataAccess/DataAccess.EntityFramework/Configurations/UserProfileConfiguration.cs
> +    private T? ConvertNullableValueObject<T>(ValueObject<T>? valueObject)
Переименовал в ConvertToNullableValueObject.

2024-08-30 08:50 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +internal class EmailValidator : IValidator<String>
string это просто алиас для System.String

2024-08-30 08:54 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/EmailValidator.cs
> +        if (value == String.Empty)
Не согласен. Знать пришёл нам null или String.Empty важно.

2024-08-30 08:56 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/FirstNameValidator.cs
> +        if (value == null)
Тут всё просто. Сам ValueObject может быть null, но Value в нём null быть не может.

2024-08-30 09:00 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryUserProfileRepository.cs
> +    : InMemoryRepository<UserProfile, Guid>(userProfiles), IUserProfileRepository
Пока никакого. Этот клас будет использоваться в тестах.

2024-08-30 09:01 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Repositories.Implementations/InMemory/InMemoryRepository.cs
> +            }
Ну хорошо.

2024-08-30 09:02 UTC, ConstantinProg commented on src/DataAccess/DataAccess.Entities/ValueObjects/Validation/UsernameValidator.cs
> +        => name.Where(ch => Char.IsLetterOrDigit(ch)).Count();
Идея хорошая. Но используется этот метод в одном месте пока.

2024-08-31 08:44 UTC, closed without merging