Add BusinessLogic.Contracts
IT-Siberians/UserProfileMicroservice pull request #5
Opened 2024-09-26 08:34 UTC by ConstantinProg

2024-09-26 14:12 UTC, m-a-ilnitsky approved these changes
PR очень короткий и не содержит логики, так что вроде даже потенциально негде ошибиться.
Вариантов кроме как принять я не вижу

2024-09-26 14:12 UTC, m-a-ilnitsky commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/UserProfileModel.cs
> +    bool IsFirstNamePublished, bool IsLastNamePublished, bool IsPhoneNumberPublished, bool IsPhotoUrlPublished)
Такой длинный список аргументов лучше писать в один столбец, тогда его проще читать.
В целом обычно удобнее располагать аргументы либо в строку, либо в столбец.
Редко бывает когда, разбивание списка аргументов одновременно на несколько строк и несколько столбцов читается хорошо.
Но я думаю это можно не исправлять

2024-09-26 14:12 UTC, m-a-ilnitsky commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/PublicUserProfileModel.cs
> +    : IModel<Guid>;
Здесь тоже лучше печатать аргументы в одни столбец.
И тогда объявление записи еще и будет больше похоже на классическое объявление класса с набором свойств

2024-09-26 14:12 UTC, m-a-ilnitsky commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/Base/IModel.cs
> +}
Пока что из кода не очевидна необходимость в этом интерфейсе.
Может он действительно не нужен... но это конечно зависит от вашей задумки

2024-09-27 09:03 UTC, oleggolen requested changes
Не очень мне опять понятно огромное количество появившихся nullable снова

2024-09-27 09:03 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/PublicUserProfileModel.cs
> +    : IModel<Guid>;
Почему опять всё nullable?

2024-09-27 09:03 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/UserProfileModel.cs
> +    bool IsFirstNamePublished, bool IsLastNamePublished, bool IsPhoneNumberPublished, bool IsPhotoUrlPublished)
Ну да я тут согласен

2024-09-27 13:19 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/PublicUserProfileModel.cs
> +    : IModel<Guid>;
В данном случае nullable это это то, что можно скрыть от публичного просмотра.

2024-09-27 17:27 UTC, closed without merging