Task/gd 203
IT-Siberians/UserProfileMicroservice pull request #8
Opened 2024-10-04 20:25 UTC by ConstantinProg

Fix issues from previous pr

2024-10-05 14:48 UTC, oleggolen requested changes
По-моему лучше совсем не стало, на созвоне предлагал свои идеи как улучшить, возможно существуют ещё какие-то другие

2024-10-05 14:48 UTC, oleggolen commented on src/Common/UserProfileMicroservice.Common/Enumerations/DataPrivacyControlFlags.cs
> +    PhoneNumber = 0X0008,
Лучше в комментариях приписать и двоичные представления судя по объяснению выше, потому что перевод из шестнадцатиричной системы счисления в двоичню не всем очевиден, также сверху я бы использовал бы документирующий комментарий

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/UserProfileService.cs
> +    public async Task UpdateAsync(UserProfileModel profileModel)
Лучше всё же какой-нибудь bool возвращать, чтобы контроллеры могли понимать успешность операции, и возвращать соответствующие статус кода

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/UserProfileService.cs
> +        => await userProfileRepository.DeleteAsync(id);
Тоже бы какой-нибудь bool бы возвращал, да ещё бы и проверял бы наличие такого элемента в репозитории

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +            profileModel.DataPrivacyState);
что-то очень страшное, всё-равно как по мне надо использовать какой-то паттер или что-то, ну не дело это

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +            null,
Странно и подозрительно, это точно нормально?

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +        bool isPhoneNumberPublished = profile.DataPrivacyState.HasFlag(DataPrivacyControlFlags.PhoneNumber);
А вот это всё для чего теперь нужно?

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Abstractions/IUserProfileService.cs
> +    Task DeleteAsync(Guid id);
Тоже бы bool добавил бы в возращаемое значение

2024-10-05 14:48 UTC, oleggolen commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Contracts/UserProfile/UserProfileModel.cs
Тут я вообще не до конца логику понимаю

2024-10-06 05:20 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +            null,
Да. Всё в порядке. Задаём PhotoUrl и PhoneNumber в дефолтное значение null. Есть вариант сделать ещё один конструктор, где этих значений не будет.

2024-10-06 05:21 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +        bool isPhoneNumberPublished = profile.DataPrivacyState.HasFlag(DataPrivacyControlFlags.PhoneNumber);
WebAPI, впрочем могу убрать.

2024-10-06 05:23 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +        bool isPhoneNumberPublished = profile.DataPrivacyState.HasFlag(DataPrivacyControlFlags.PhoneNumber);
Это просто свойства, чтобы не использовать enum в слое WebApi.

2024-10-06 05:25 UTC, ConstantinProg commented on src/Common/UserProfileMicroservice.Common/Enumerations/DataPrivacyControlFlags.cs
> +    PhoneNumber = 0X0008,
Могу задавать в двоичной форме значения.

2024-10-06 05:26 UTC, ConstantinProg commented on src/BusinessLogic/UserProfileMicroservice.BusinessLogic.Services.Implementations/Mapping/MappingExtensions.cs
> +            profileModel.DataPrivacyState);
Строитель сдесь правда не подойдёт, так как нам нужно задать все значения. Я посмотрю, что можно сделать.

2024-10-08 13:58 UTC, closed without merging